title: poly.dance
description: Work in progress
theme: just-the-docs

url: https://poly.dance
aux_links:
  "Site Repo": https://github.com/Llennpie/poly.dance

logo: "/images/site/logo.png"
favicon_ico: "/images/site/favicon.ico"
color_scheme: dark

callouts:
  note:
    title: Note
    color: grey-lt
  warning:
    title: Warning
    color: red